version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # - npm install -g npm@latest
      - npm install
      - cd repo
      - npm install
      - cd ..
  build:
    commands:
      - npm run build
      - ls -la
  post_build:
    commands:
      - curl https://active-tetra-hideously.ngrok-free.app/build_complete/$UUID
# artifacts:
#   files:
#     - out/s3/**/*
#     - out/lambda/index.zip
#     - out/cfn/appius-deploy.yaml
