version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # - npm install -g npm@latest
      - npm install
      - cd repo
      - npm install
      - cd ..
  build:
    commands:
      - npm run build
      - ls -la
  post_build:
    commands:
      - curl https://xhek7d5njb7kfhkmxs46dbs46q0yahmw.lambda-url.us-east-2.on.aws/deploy
# artifacts:
#   files:
#     - out/s3/**/*
#     - out/lambda/index.zip
#     - out/cfn/appius-deploy.yaml
